In [1]:
import pandas as pd

# Preguntas de análisis usando los archivos .parquet

Leer y almacenar el contenido de los archivos

In [2]:
data_categories = pd.read_parquet('categorias.parquet')

data_books = pd.read_parquet('libros.parquet')

In [3]:
data_categories.head()

,categoria,url_categoria,cantidad_libros,fecha_extraccion,extraido_por
0,Travel,https://books.toscrape.com/catalogue/category/...,11,2026-08-08 12:01:33.401756,Miguel Zuleta
1,Mystery,https://books.toscrape.com/catalogue/category/...,32,2026-08-08 12:01:34.064678,Miguel Zuleta
2,Historical Fiction,https://books.toscrape.com/catalogue/category/...,26,2026-08-08 12:01:34.841400,Miguel Zuleta
3,Sequential Art,https://books.toscrape.com/catalogue/category/...,75,2026-08-08 12:01:35.530058,Miguel Zuleta
4,Classics,https://books.toscrape.com/catalogue/category/...,19,2026-08-08 12:01:36.110119,Miguel Zuleta

In [4]:
data_books.tail()

,upc,titulo,categoria,descripcion,tipo_producto,precio_sin_impuesto,precio_con_impuesto,impuesto,moneda,disponibilidad,cantidad_stock,calificacion,cantidad_resenas,url_libro,url_imagen,fecha_extraccion,extraido_por
995,cd2a2a70dd5d176d,Alice in Wonderland (Alice's Adventures in Won...,Classics,,Books,55.53,55.53,0.0,GBP,In stock (1 available),1,1,0,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/99/df/9...,2026-08-08 12:11:04.083679,Miguel Zuleta
996,bfd5e1701c862ac3,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Sequential Art,High school student Kei Nagai is struck dead i...,Books,57.06,57.06,0.0,GBP,In stock (1 available),1,4,0,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/30/98/3...,2026-08-08 12:11:04.529073,Miguel Zuleta
997,19fec36a1dfb4c16,A Spy's Devotion (The Regency Spies of London #1),Historical Fiction,"In England’s Regency era, manners and elegance...",Books,16.97,16.97,0.0,GBP,In stock (1 available),1,5,0,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/f9/6b/f...,2026-08-08 12:11:04.972107,Miguel Zuleta
998,f684a82adc49f011,1st to Die (Women's Murder Club #1),Mystery,"James Patterson, bestselling author of the Ale...",Books,53.98,53.98,0.0,GBP,In stock (1 available),1,1,0,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/f6/8e/f...,2026-08-08 12:11:05.259886,Miguel Zuleta
999,228ba5e7577e1d49,"1,000 Places to See Before You Die",Travel,"Around the World, continent by continent, here...",Books,26.08,26.08,0.0,GBP,In stock (1 available),1,5,0,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/9e/10/9...,2026-08-08 12:11:05.685220,Miguel Zuleta

## ¿Cuántas categorías de libros existen?

In [17]:
cantidad_categorias = len(data_categories)
print(cantidad_categorias)

50

Existen 50 categorías de libros

## ¿Cuántos libros hay en cada categoría?

In [21]:
data_categories[['categoria', 'cantidad_libros']]

             categoria  cantidad_libros
0               Travel               11
1              Mystery               32
2   Historical Fiction               26
3       Sequential Art               75
4             Classics               19
5           Philosophy               11
6              Romance               35
7       Womens Fiction               17
8              Fiction               65
9            Childrens               29
10            Religion                7
11          Nonfiction              110
12               Music               13
13             Default              152
14     Science Fiction               16
15    Sports and Games                5
16       Add a comment               67
17             Fantasy               48
18           New Adult                6
19         Young Adult               54
20             Science               14
21              Poetry               19
22          Paranormal                1
23                 Art                8
24          Psychology                7
25       Autobiography                9
26           Parenting                1
27       Adult Fiction                1
28               Humor               10
29              Horror               17
30             History               18
31      Food and Drink               30
32   Christian Fiction                6
33            Business               12
34           Biography                5
35            Thriller               11
36        Contemporary                3
37        Spirituality                6
38            Academic                1
39           Self Help                5
40          Historical                2
41           Christian                3
42            Suspense                1
43       Short Stories                1
44              Novels                1
45              Health                4
46            Politics                3
47            Cultural                1
48             Erotica                1
49               Crime                1

## ¿Cuál es el libro más caro?

In [20]:
precio_maximo = data_books["precio_con_impuesto"].max()

libros_mas_caros = data_books[data_books["precio_con_impuesto"] == precio_maximo]

libros_mas_caros[["titulo", "precio_con_impuesto"]]

                                 titulo  precio_con_impuesto
648  The Perfect Play (Play by Play #1)                59.99

The Perfect Play (Play by Play #1) es el libro más caro, con un precio de £59.59

## ¿Hay algún libro que aparezca en más de una categoría?

In [23]:
duplicados = data_books[data_books["upc"].duplicated(keep=False)]

duplicados[["upc", "titulo", "categoria"]].sort_values("upc")

Empty DataFrame
Columns: [upc, titulo, categoria]
Index: []

In [25]:
cantidad = data_books[data_books["upc"].duplicated()]["upc"].nunique()

print(cantidad)

0

Esto solo significa que no hay UPC repetidos (lo cual, para el dataset actual. significa que no hay libros que pertenezcan a más de una categoría), pero es el único análisis posible con respecto al upc, a pesar de que puede no ser muy informativo considerando el hecho de que el proceso de extracción solo conserva una fila por UPC.

## ¿Cuál es el libro más barato de cada categoría?

In [28]:
precios_minimos = data_books.groupby("categoria")["precio_con_impuesto"].transform("min")

libros_mas_baratos = data_books[
    data_books["precio_con_impuesto"] == precios_minimos
]

libros_mas_baratos[[
    "categoria",
    "titulo",
    "precio_con_impuesto"
]].sort_values("categoria")

,categoria,titulo,precio_con_impuesto
616,Academic,Logan Kade (Fallen Crest High #5.5),13.12
716,Add a comment,The Tipping Point: How Little Things Can Make ...,10.02
844,Adult Fiction,Fifty Shades Freed (Fifty Shades #3),15.36
479,Art,History of Beauty,10.29
163,Autobiography,The Argonauts,10.93
182,Biography,Louisa: The Extraordinary Life of Mrs. Adams,16.85
138,Business,The Third Wave: An Entrepreneur’s Vision of th...,12.61
858,Childrens,Counting Thyme,10.62
539,Christian,Blue Like Jazz: Nonreligious Thoughts on Chris...,25.77
537,Christian Fiction,Counted With the Stars (Out from Egypt #1),17.97
652,Classics,The Hound of the Baskervilles (Sherlock Holmes...,14.82
699,Contemporary,We Are All Completely Beside Ourselves,24.04
152,Crime,The Long Shadow of Small Ghosts: Murder and Me...,10.97
212,Cultural,Amid the Chaos,36.58
302,Default,Greek Mythic History,10.23
200,Erotica,Dark Notes,19.19
535,Fantasy,Every Heart a Doorway (Every Heart A Doorway #1),12.16
297,Fiction,I Am Pilgrim (Pilgrim #1),10.60
590,Food and Drink,The Power Greens Cookbook: 140 Delicious Super...,11.05
69,Health,The Bulletproof Diet: Lose up to a Pound a Day...,49.05
557,Historical,The Girl You Left Behind (The Girl You Left Be...,15.79
507,Historical Fiction,The Constant Princess (The Tudor Court #1),16.62
485,History,Brilliant Beacons: A History of the American L...,11.45
274,Horror,Pet Sematary,10.56
277,Humor,Old School (Diary of a Wimpy Kid #10),11.83
663,Music,Orchestra of Exiles: The Story of Bronislaw Hu...,12.36
258,Mystery,Tastes Like Fear (DI Marnie Rome #3),10.69
932,New Adult,The Hook Up (Game On #1),36.29
392,Nonfiction,"The Sleep Revolution: Transforming Your Life, ...",11.68
432,Novels,Suzie Snowflake: One beautiful flake (a self-e...,54.81
907,Paranormal,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40
862,Parenting,Catastrophic Happiness: Finding Joy in Childho...,37.35
34,Philosophy,Sophie's World,15.94
176,Poetry,Poems That Make Grown Women Cry,14.19
18,Politics,Libertarianism for Beginners,51.33
242,Psychology,The Lucifer Effect: Understanding How Good Peo...,10.40
128,Religion,You Are What You Love: The Spiritual Power of ...,21.87
789,Romance,Reservations for Two,11.10
501,Science,The Origin of Species,10.01
144,Science Fiction,The Project,10.65
492,Self Help,You Are a Badass: How to Stop Doubting Your Gr...,12.08
84,Sequential Art,Patience,10.16
454,Short Stories,The Grownup,35.88
30,Spirituality,The Four Agreements: A Practical Guide to Pers...,17.66
892,Sports and Games,Sugar Rush (Offensive Line #2),24.42
458,Suspense,Silence in the Dark (Logan Point #4),58.33
20,Thriller,In Her Wake,12.84
723,Travel,The Road to Little Dribbling: Adventures of an...,23.21
659,Womens Fiction,Some Women,13.73
638,Young Adult,An Abundance of Katherines,10.00

## ¿Cuánto más caro o más barato es cada libro respecto al precio promedio de su categoría?

In [30]:
promedio_categoria = data_books.groupby("categoria")["precio_con_impuesto"].transform("mean")

data_books["diferencia_precio"] = (
    data_books["precio_con_impuesto"] - promedio_categoria
)

data_books[[
    "categoria",
    "titulo",
    "precio_con_impuesto",
    "diferencia_precio"
]]

,categoria,titulo,precio_con_impuesto,diferencia_precio
0,Poetry,A Light in the Attic,51.77,15.795789
1,Historical Fiction,Tipping the Velvet,53.74,20.095769
2,Fiction,Soumission,50.10,14.033385
3,Mystery,Sharp Objects,47.82,16.100938
4,History,Sapiens: A Brief History of Humankind,54.23,16.935000
...,...,...,...,...
995,Classics,Alice in Wonderland (Alice's Adventures in Won...,55.53,18.984737
996,Sequential Art,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,22.487733
997,Historical Fiction,A Spy's Devotion (The Regency Spies of London #1),16.97,-16.674231
998,Mystery,1st to Die (Women's Murder Club #1),53.98,22.260937
999,Travel,"1,000 Places to See Before You Die",26.08,-13.714545

## Mayor ingreso potencial por categoría

In [36]:
data_books["ingreso_potencial"] = (
    data_books["precio_con_impuesto"] * data_books["cantidad_stock"]
)

ingreso_maximo = data_books.groupby("categoria")["ingreso_potencial"].transform("max")

libros_mayor_ingreso = data_books[
    data_books["ingreso_potencial"] == ingreso_maximo
]

libros_mayor_ingreso[[
    "categoria",
    "titulo",
    "precio_con_impuesto",
    "cantidad_stock",
    "ingreso_potencial"
]].sort_values("categoria")

,categoria,titulo,precio_con_impuesto,cantidad_stock,ingreso_potencial
616,Academic,Logan Kade (Fallen Crest High #5.5),13.12,5,65.60
97,Add a comment,Judo: Seven Steps to Black Belt (an Introducto...,53.90,16,862.40
844,Adult Fiction,Fifty Shades Freed (Fifty Shades #3),15.36,3,46.08
29,Art,Wall and Piece,44.18,18,795.24
405,Autobiography,Lab Girl,40.85,11,449.35
540,Biography,Benjamin Franklin: An American Life,48.19,7,337.33
6,Business,The Dirty Little Secrets of Getting Your Dream...,33.34,19,633.46
25,Childrens,Birdsong: A Story in Pictures,54.64,19,1038.16
127,Christian,(Un)Qualified: How God Uses Broken People to D...,54.00,16,864.00
202,Christian Fiction,Close to You,49.46,15,741.90
684,Classics,Candide,58.63,4,234.52
265,Contemporary,Someone Like You (The Harrisons #2),52.79,14,739.06
152,Crime,The Long Shadow of Small Ghosts: Murder and Me...,10.97,15,164.55
212,Cultural,Amid the Chaos,36.58,15,548.70
27,Default,Aladdin and His Wonderful Lamp,53.13,19,1009.47
200,Erotica,Dark Notes,19.19,15,287.85
91,Fantasy,Masks and Shadows,56.40,16,902.40
2,Fiction,Soumission,50.10,20,1002.00
57,Food and Drink,The Pioneer Woman Cooks: Dinnertime: Comfort C...,56.41,16,902.56
69,Health,The Bulletproof Diet: Lose up to a Pound a Day...,49.05,16,784.80
340,Historical,All the Light We Cannot See,29.87,14,418.18
1,Historical Fiction,Tipping the Velvet,53.74,20,1074.80
4,History,Sapiens: A Brief History of Humankind,54.23,20,1084.60
75,Horror,Security,39.25,16,628.00
243,Humor,The Long Haul (Diary of a Wimpy Kid #9),44.07,14,616.98
15,Music,Our Band Could Be Your Life: Scenes from the A...,57.25,19,1087.75
3,Mystery,Sharp Objects,47.82,20,956.40
150,New Adult,The Matchmaker's Playbook (Wingmen Inc. #1),55.85,15,837.75
67,Nonfiction,The Electric Pencil: Drawings from Inside Stat...,56.06,16,896.96
432,Novels,Suzie Snowflake: One beautiful flake (a self-e...,54.81,9,493.29
907,Paranormal,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40,1,15.40
862,Parenting,Catastrophic Happiness: Finding Joy in Childho...,37.35,3,112.05
68,Philosophy,The Death of Humanity: and the Case for Life,58.11,16,929.76
0,Poetry,A Light in the Attic,51.77,22,1138.94
18,Politics,Libertarianism for Beginners,51.33,19,975.27
407,Psychology,It Didn't Start with You: How Inherited Family...,56.27,11,618.97
110,Religion,Don't Be a Jerk: And Other Practical Advice fr...,37.97,16,607.52
165,Romance,Suddenly in Love (Lake Haven #1),55.99,15,839.85
100,Science,Immunity: How Elie Metchnikoff Changed the Cou...,57.36,16,917.76
17,Science Fiction,Mesaerion: The Best Science Fiction Stories 18...,37.59,19,714.21
87,Self Help,Online Marketing for Busy Authors: A Step-By-S...,46.35,16,741.60
13,Sequential Art,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,19,993.51
454,Short Stories,The Grownup,35.88,8,287.04
203,Spirituality,Chasing Heaven: What Dying Taught Me About Living,37.80,15,567.00
842,Sports and Games,"Friday Night Lights: A Town, a Team, and a Dream",51.22,3,153.66
458,Suspense,Silence in the Dark (Logan Point #4),58.33,8,466.64
38,Thriller,Behind Closed Doors,52.22,18,939.96
19,Travel,It's Only the Himalayas,45.17,19,858.23
186,Womens Fiction,I Had a Nice Time And Other Lies...: How to fi...,57.36,15,860.40
337,Young Adult,Aristotle and Dante Discover the Secrets of th...,58.14,14,813.96